### PR TITLE
Provide more detailed on-chain error messages for failed API calls

### LINKED ISSUE #1502: Improve on-chain error message for failed API calls
## Steps to reproduce

Run the `coingecko` integration in `airnode-examples`, but in `integrations/coingecko/request-utils.ts` replace `Ethereum` with `Bthereum` (or any other non-existent coin) as the `coinLabel`.

## Present Behaviour

I performed the simple "mistake" listed above, which obviously caused the API call to fail. The [on-chain fail tx errorMessage](https://goerli.etherscan.io/tx/0x4c76b38e61f538dccc164a094c9ccca013ec6a474ffd7e025ea94e25d57a2ad5) was, somewhat unhelpfully:

```
API call failed
```

## Desired Behaviour

A user who make an error in the request could be provided with better on-chain error messages and Airnode has the ability to report more detailed errors, for example the below `ERROR AxiosError: Request failed with status code 404`. A `404` would be helpful as the user could then ask themselves why might the page not be found and re-check their request. Full log below:

```
[2022-10-24 06:50:02.261] INFO Created initial coordinator state                                                Coordinator-ID:0d74c006d6367893
[2022-10-24 06:50:02.265] INFO Forking to initialize providers                                                  Coordinator-ID:0d74c006d6367893
[2022-10-24 06:50:03.997] INFO Pending requests: 1 API call(s), 0 withdrawal(s)                                 Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider
[2022-10-24 06:50:04.330] INFO Forking to initialize providers complete                                         Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider
[2022-10-24 06:50:04.331] INFO Initialized EVM provider:exampleProvider                                         Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider
[2022-10-24 06:50:04.331] INFO Applying chain request limits                                                    Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider
[2022-10-24 06:50:04.338] INFO Applied chain request limits                                                     Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider
[2022-10-24 06:50:04.340] INFO Aggregated API calls                                                             Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider
[2022-10-24 06:50:06.345] ERROR Failed to call Endpoint:coinMarketData                                           Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4
[2022-10-24 06:50:06.345] ERROR AxiosError: Request failed with status code 404
    at settle (/usr/local/share/.config/yarn/global/node_modules/axios/dist/node/axios.cjs:1268:12)
    at BrotliDecompress.handleStreamEnd (/usr/local/share/.config/yarn/global/node_modules/axios/dist/node/axios.cjs:2446:11)
    at BrotliDecompress.emit (events.js:412:35)
    at BrotliDecompress.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4
[2022-10-24 06:50:06.346] INFO Processing 1 pending API call(s)...                                              Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4
[2022-10-24 06:50:06.347] ERROR API call to Endpoint:coinMarketData errored after 2000ms with error message:API call failed Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4
[2022-10-24 06:50:06.347] INFO Received 0 successful API call(s)                                                Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4
[2022-10-24 06:50:06.347] INFO Received 1 errored API call(s)                                                   Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4
[2022-10-24 06:50:06.355] INFO Executed API calls                                                               Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4
[2022-10-24 06:50:06.357] INFO Disaggregated API calls                                                          Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4
[2022-10-24 06:50:06.359] INFO Forking to submit transactions for EVM provider: exampleProvider and sponsor: 0x2E103c7502c1cAd0c11404F17D7C6339Db65626f... Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4
[2022-10-24 06:50:07.578] INFO Strategy (latestBlockPercentileGasPrice) gas price set to 13.337406323 gwei.     Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4, Sponsor-Address:0x2E103c7502c1cAd0c11404F17D7C6339Db65626f
[2022-10-24 06:50:07.923] INFO Submitting API call fail for Request:0x00f719b3a36ff1aa31688850eada14fe4061a5c712d681350d39ba17e1d874c3... Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4, Sponsor-Address:0x2E103c7502c1cAd0c11404F17D7C6339Db65626f
[2022-10-24 06:50:07.923] INFO Transaction:0x4c76b38e61f538dccc164a094c9ccca013ec6a474ffd7e025ea94e25d57a2ad5 submitted for Request:0x00f719b3a36ff1aa31688850eada14fe4061a5c712d681350d39ba17e1d874c3 Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4, Sponsor-Address:0x2E103c7502c1cAd0c11404F17D7C6339Db65626f
[2022-10-24 06:50:07.937] INFO Forking to submit transactions complete                                          Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4, Sponsor-Address:0x2E103c7502c1cAd0c11404F17D7C6339Db65626f
[2022-10-24 06:50:07.939] INFO Coordinator completed at 2022-10-24 06:50:07. Total time: 5679ms                 Coordinator-ID:0d74c006d6367893, Chain-ID:5, Provider:exampleProvider, Endpoint-ID:0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4, Sponsor-Address:0x2E103c7502c1cAd0c11404F17D7C6339Db65626f
```

### PR DESCRIPTION
**Pull request by dcroote**
Closes #1502.

Adds 3 possible error messages depending on the `AxiosError` (note the API error message is not being relayed to avoid publishing sensitive information as explained in [this comment](https://github.com/api3dao/airnode/issues/1502#issuecomment-1288857455)):
- "with status code X"
- "with no response"
- "in building the request"

Tested with the `airnode-client-dev` image on Goerli with the same setup as described in #1502 and the [error message now includes the 404 status code](https://goerli.etherscan.io/tx/0x425d2c9bb269765d24ee11ba4f078a66b38832a567f358c0119f1a8f5b4e611a) for the price request of a nonexistent coin:
```
API call failed with status code 404
```

### CODE REVIEW

File: packages/airnode-node/src/api/index.ts [hunk 1]
```diff
@@ -198,7 +209,10 @@ export async function performApiCall(
   if (!goRes.success) {
     const { aggregatedApiCall } = payload;
     const log = logger.pend('ERROR', `Failed to call Endpoint:${aggregatedApiCall.endpointName}`, goRes.error);
-    return [[log], { success: false, errorMessage: `${RequestErrorMessage.ApiCallFailed}` }];
+    // eslint-disable-next-line import/no-named-as-default-member
+    const axiosErrorMsg = axios.isAxiosError(goRes.error) ? errorMsgFromAxiosError(goRes.error) : '';
+    const errorMessage = [RequestErrorMessage.ApiCallFailed, axiosErrorMsg].filter(Boolean).join(' ');
```
Comment (amarthadan) [inline packages/airnode-node/src/api/index.ts:214]: You can use [lodash compact](https://lodash.com/docs/4.17.15#compact) instead of `filter(Boolean)`. It's imo more readable but I'll leave it up to you.

File: packages/airnode-node/src/api/index.ts [hunk 2]
```diff
@@ -184,6 +185,16 @@ export function isPerformApiCallFailure(
   return !!(value as ApiCallErrorResponse).errorMessage;
 }
 
+export function errorMsgFromAxiosError(e: AxiosError): string {
+  if (e.response) {
+    return `with status code ${e.response.status}`;
+  } else if (e.request) {
+    return 'with no response';
+  } else {
+    return 'in building the request';
```
Comment (amarthadan) [inline packages/airnode-node/src/api/index.ts:194]: Hmm. At first glance at the error message, I thought that the airnode-adapter was not able to build a request based on the OIS. But that's not what the message is trying to convey. But I can't come up with a better wording tbh :sweat_smile: Maybe I'm just reading too much into it. WDYT?

Comment (dcroote) [reply packages/airnode-node/src/api/index.ts:194]: The [axios error handling docs](https://axios-http.com/docs/handling_errors) don't help us out much either 😅 
```ts
  } else {
      // Something happened in setting up the request that triggered an Error
      console.log('Error', error.message);
  }
```

How about: 'in building the *http* request`?

File: packages/airnode-node/src/api/index.ts (hunk 1 above)
Comment (dcroote) [reply packages/airnode-node/src/api/index.ts:214]: Thanks and will do 👍

File: packages/airnode-node/src/api/index.ts (hunk 2 above)
Comment (amarthadan) [reply packages/airnode-node/src/api/index.ts:195]: Maybe `while establishing the connection`? But `in building the HTTP request` is fine as well. I wouldn't mention the Axios specifically though.

**Review by amarthadan — APPROVED** [review]
I'm leaving the wording of the error message up to you. Other than that LGTM.

**Comment by martinkolenic** [comment]
Hi @dcroote, I am currently testing the issue and wanted to ask about when to expect the error in building the request and how that can be repreoduced. I'm using Beeceptor to mock responses and this works with returning a status code. Could you please advise?

I'm also thinking it could be practical to return all or at least several more error status codes (say, there's the openweather example and when you have a bad api key, it sends back an error status code so knowing that could be quite informative for the user).

**Comment by dcroote** [comment]
Hi @martinkolenic - of the three error messages added ("with status code X", "with no response", and "in building the request"), the first two are the most relevant to test, with the third considered an unlikely fallback. I haven't used Beeceptor, but if you could return different status codes from the API, those should appear in the error message written on chain, like for [this Goerli transaction](https://goerli.etherscan.io/tx/0x425d2c9bb269765d24ee11ba4f078a66b38832a567f358c0119f1a8f5b4e611a#eventlog). For the second error message, I imagine that could be tested if Beeceptor has a way to have a long delay / timeout in responding to a request.

**Comment by martinkolenic** [comment]
Hi Derek, thanks for the information. Beeceptor does allow delayed responses and setting it to about 600 actually did the trick. Here's a formal test report:

**Test 1: Check for status code messages**
Environment: local eth node, local Airnode, beeceptor API response mocking

Steps: Modify the coingecko example to send requests to a mock Beeceptor endpoint, set up the endpoint to return the 404 code for any request; make request with the local Airnode; change to another code and repeat the request

Expected result: Receive more informative error messages for status codes 404, 301, 403 and 409
Actual result: Matches expected results

**Test 2: Check for timeout message presence**
Environment: local eth node, local Airnode, beeceptor API response mocking

Steps: Modify the coingecko example to send requests to a mock Beeceptor endpoint, set up the endpoint to return a 200 code with a 600 second response; make request with the local Airnode; wait if the request times out

Expected result: Receive a timeout message
Actual result: Matches expected results
